### ISSUE TITLE
Add virtual chassis logic to interface sync

### ISSUE THREAD

**Issue by bonzo81** [bonzo81/netbox-librenms-plugin#3]
### NetBox Librenms Plugin version

v0.2.3

### NetBox version

v4.0

### Feature type

New functionality

### Proposed functionality

If a device is part of a virtual chassis, allow the selection of a virtual chassis member when syncing the interface in the interface row.

Add a drop down to the interface row to allow selection of another virtual chassis member.

When the interface is synced apply interface to that member.

Only display the virtual chassis drop column if device is part of a virtual chassis in netbox 

### Use case

This would be helpful for stacked network switches like Cisco catalyst 9300 or 9200s

**Comment by Mukku27** [comment]
@bonzo81   i would like to work on it please assign it to me

**Comment by bonzo81** [comment]
Hi @Mukku27

Thanks for offering to work on this issue. I have assigned it to you. Please feel free to chat here if any clarification is needed.

**Comment by bonzo81** [comment]
Completed with PR #20
