### ISSUE TITLE
Select all for interface sync not working

### ISSUE THREAD

**Issue by bonzo81** [bonzo81/netbox-librenms-plugin#4]
### NetBox Librenms Plugin version

v0.2.3

### NetBox version

V4.1

### Python version

3.10

### Steps to Reproduce

On interface sync page. Click top checkbox to select all interfaces in table but nothing happens.

### Expected Behavior

All interfaces are selected

### Observed Behavior

Nothing selected

**Comment by bonzo81** [comment]
@donmart85

**Comment by donmart85** [comment]
Hi,

i have solved with this modify.
Could you check it?

Thanks.

[m2-check all interface.txt](https://github.com/user-attachments/files/17363425/m2-check.all.interface.txt)
