### ISSUE TITLE
interface name device not correct

### ISSUE THREAD

**Issue by donmart85** [bonzo81/netbox-librenms-plugin#49]
### NetBox Librenms Plugin version

v0.2.9

### NetBox version

v4.1.7

### Python version

3.11

### Steps to Reproduce

When i do a sync interface on a windows server, it get hardware name and not Ethernet name.

![immagine](https://github.com/user-attachments/assets/61f3eb3f-eadb-4004-a230-f982cd962159)
![immagine](https://github.com/user-attachments/assets/65c182be-85b6-4799-b0a2-32535132269d)

i have this problem also with cisco device. 

![immagine](https://github.com/user-attachments/assets/ccdc63b2-dfd1-4e33-b437-91082100adeb)
![immagine](https://github.com/user-attachments/assets/4d54983c-68e4-4f81-ba49-b40c76364d00)

I haven't this problem with linux device.

![immagine](https://github.com/user-attachments/assets/95e13b66-e90a-4d57-8dc3-f377606e3cd7)
![immagine](https://github.com/user-attachments/assets/28f60a4e-3871-44e1-b9ea-4e551bd0c456)

### Expected Behavior

i expect as correct name the ethernet port name (as in librenms) and not hardware name. 
I would use phisycal name for Label field.
![immagine](https://github.com/user-attachments/assets/97b28d0b-a59b-4d49-a0b8-f8984b9abfb8)

For example in Cisco device, there's problem also for Cabling Sync, because it found the interface remote port is Gi (Gi10 in example) and not Gigabithethernet. in this case i can't sync cable.
![immagine](https://github.com/user-attachments/assets/98d40e89-a014-46bd-85f4-33246890f6e7)

### Observed Behavior

i have hardware name in interface name.

**Comment by bonzo81** [comment]
Hi @donmart85,

I think this will become a plugin setting, as well as an override option on each table pages. 

Here is my thinking...

1. The LibreNMS API has two possible values available for the interface name in NetBox. Either ifName or ifDescr.  Sometimes they are the same value, but sometime they are different. 

Here is an example from a Cisco 9k switch: (different values)

```json
{
        {
            "port_id": 5760,
            "ifName": "Gi0/3",
            "ifDescr": "GigabitEthernet0/3",
            "ifType": "ethernetCsmacd",
            "ifSpeed": 10000000,
            "ifAdminStatus": "up",
        },
```
... and here's a Ubuiqiti switch port. (different values)
```json
        {
            "port_id": 659,
            "ifName": "CPU Interface:  5/1",
            "ifDescr": "CPU Interface for Slot: 5 Port: 1",
            "ifType": "other",
            "ifSpeed": null,
            "ifAdminStatus": "up",
        },
```
A different Ubuiqiti device (same values)
```json
        {
            "port_id": 647,
            "ifName": "eth0",
            "ifDescr": "eth0",
            "ifType": "ethernetCsmacd",
            "ifSpeed": 1000000000,
            "ifAdminStatus": "up",
        },
```


2. The port name displayed in LibreNMS is not always available in the API ifName or ifDescr field. For example the above Ubuiqiti switch port (second example) displays like this in LibreNMS. It does not match either ifName or ifDescr.
<img width="571" alt="{5AE2A944-F2BE-4AFC-9FB5-E7455B1EE772}" src="https://github.com/user-attachments/assets/1498614e-93ad-44c2-9ac6-5afd51a600e3">


3. I would like to match the interface naming conventions used in the NetBox [device type library](https://github.com/netbox-community/devicetype-library/tree/master/device-types) when possible. For my environment (mainly Cisco) it was the ifDescr value that matched.
4. I also think there is user preference too. One may prefer Gi1/0/1 over GigabitEthernet1/0/1 in NetBox and vice versa.


Clearly using ifDescr isn't going to be the right option for all devices and neither would using ifName. So I think making this an option when creating the tables would help.

As there are vendor inconsistences, API variations, and user preference to consider, I think making ifName or ifDescr a user option is the only way forward at the moment.

**Comment by donmart85** [comment]
Hi @bonzo81, 

you're right, maybe the best option is that users choose the prefered name. 
However often the ifDescr is too long (as windows or Ubiquiti), i would left ifName as predefined.
I think that the scope of this plugin should be the integration between netbox and librenms, so the interface name should be the same in both systems. It is my idea.

OFF TOPIC...what is your opinion about ubiquity switch? are they work well? how are they monitored in LibreNMS (interfaces, FDP Table, arp table, ecc)? i have cisco small business but they are expensive, so i would want to change brand.
I'm just using ubiquity's ap and they work well, with a docker container as controller.

Thank you for your work, the plugin works very well.

**Comment by bonzo81** [comment]
Hi @donmart85,

Sorry for slow reply, I've been working on the plugin.

I've got a new setting in place for the plugin that should help with this. Can be set in the plugin config
```bash
PLUGINS_CONFIG = {
    'netbox_librenms_plugin': {
        'librenms_url': 'https://your-librenms-instance.com',
        'api_token': 'your_librenms_api_token',
        'cache_timeout': 300,
        'verify_ssl': False,
        'interface_name_field': 'ifDescr', # Optional: Set default name field for interface name. ifName used as default
    }
}
```

Also providing an option to override this per device. 
<img width="420" alt="image" src="https://github.com/user-attachments/assets/a8acb270-c217-4ac1-b824-60ee10819886" />

This should be in the next release 0.3.0 is the next few days.

Regarding Ubuiqiti, I only have a handful of devices in my house. I don't have any experience at the small business or enterprise level with them. For my own purposes they work well and are easy to setup and monitor through the Unifi app/website. In LIbreNMS there is interface, FDB and ARP data available.

Thanks for you feedback for the plugin. Hopefully the next release is helpful for you.
