### ISSUE TITLE
Add Mac address to interface table and sync  data 

### ISSUE THREAD

**Issue by bonzo81** [bonzo81/netbox-librenms-plugin#5]
### NetBox Librenms Plugin version

v0.2.3

### NetBox version

V4.1

### Feature type

New functionality

### Proposed functionality

Add interface Mac address to the interface sync table and sync data.

### Use case

Useful and unique interface data

**Comment by bonzo81** [comment]
@donmart85

**Comment by donmart85** [comment]
Hi,

I'm trying to learn python (with ChatGPT help XD).
I would propose modified file for syncing mac address (tables.py and utils.py).
In my lab it seems working.
Could you check it?

Thanks.

Regards.

[modifica mac address.txt](https://github.com/user-attachments/files/17310190/modifica.mac.address.txt)
